id: ADC02E999
title: In Praise of the Goddess Mārīcī (Özerchenma)
type: translation
pechas:
- I3FCC9959
- I1603B08F
- IA72427A0
- I49D39997
- IAF43B4CC
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:43:29.059897
  last_modified_at: 2023-01-04 12:43:29.059914
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I3FCC9959/CF91: '3350'
  I1603B08F/B3BC: '3350'
  IA72427A0/41B0: '3350'
  I49D39997/83CC: '3350'
  IAF43B4CC/2251: '3350'
